### ISSUE TITLE
Pasting clipping in a web page inside a frame doesn't work in Clippings 5.1

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings#72]
A user has reported that clipping paste doesn't work at all when a web page textbox (or rich text editor) is in a web page that is inside a frame (i.e., the HTML page is in a <frame> within a <frameset> document).

The issue goes away when right-clicking on the page and selecting This Frame -> Open Frame In New Tab (or Open Frame In New Window).

**Comment by aecreations** [comment]
In the Clippings frame script (aeFrameModule.js), `frameGlobal.content.document.activeElement` returns an HTMLFrameElement DOM object, when focus is inside a textbox or rich text editor in a web page that is inside a frame.

I tried the following, but it doesn't work:
```
let activeElt = frameGlobal.content.document.activeElement;
let focusedElt = activeElt.querySelector(":focus");  // focusedElt is null
```

**Comment by bschmalhofer** [comment]
Thanks, the issue is fixed in Clippings 5.1.1.

**Comment by aecreations** [comment]
Just to be clear, the fix that shipped with Clippings 5.1.1 allows users to create a clipping from selected text on a web page (not inside a textbox or rich text editor), when the web page is inside an HTML frame.
However, there is still an issue (which is the topic of this Github issue ticket) with creating or pasting a clipping from text inside a text box or rich text editor on a web page inside an HTML frame.  Workaround instructions can be found here: http://aecreations.blogspot.ca/2016/07/coming-soon-clippings-511.html
